services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: nastenysh
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: studs
    ports:
      - "15432:5432"
