spring:
  application:
    name: is-lab1

  jpa:
    # Set to use EclipseLink as JPA provider
    provider: org.eclipse.persistence.jpa.JpaPersistenceProvider
    generate-ddl: ${SPRING_JPA_GENERATE_DDL:true}
    ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

    #configure EclipseLink
    properties:
      javax.persistence.schema-generation.database.action: create
      javax.persistence.jdbc.driver: org.postgresql.Driver
      javax.persistence.jdbc.url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/studs}
      javax.persistence.jdbc.user: ${SPRING_DATASOURCE_USERNAME:s368149}
      javax.persistence.jdbc.password: ${SPRING_DATASOURCE_PASSWORD:A4diwszNUMbJj7s9}
      eclipse.link.logging.level: FINE
      eclipse.link.jdbc.timezone: UTC

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/studs}
    username: ${SPRING_DATASOURCE_USERNAME:s368149}
    password: ${SPRING_DATASOURCE_PASSWORD:A4diwszNUMbJj7s9}

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${APPLICATION_SECURITY_EXPIRATION:86400000} # a day
    password-min-length: 8
server:
  port: 24727
